[package]
name = "interpreter"
version = "0.1.0"
authors = ["Alan Gan <alanrgan@gmail.com>"]

features = ["clippy", "test"]

[dependencies]
clippy = {version = "*", optional = true}
itertools = "*"

[features]
test = []